# Generated by Django 4.1.1 on 2022-09-15 01:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0006_alter_servidor_setor'),
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('equipamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipamento.equipamento')),
                ('data_de_emprestimo', models.DateField(default=datetime.date(2022, 9, 14))),
                ('data_de_devolucao', models.DateField()),
                ('servidor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servidor.servidor')),
            ],
            bases=('equipamento.equipamento',),
        ),
    ]
