# Generated by Django 4.1.1 on 2022-09-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0002_emprestimo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprestimo',
        ),
    ]
