# Generated by Django 4.1.1 on 2022-09-15 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0006_alter_emprestimo_id_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='id_equipamento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamento.equipamento'),
        ),
    ]
