# Generated by Django 4.1.1 on 2022-09-17 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0007_alter_emprestimo_id_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_de_emprestimo',
            field=models.DateField(default=datetime.datetime(2022, 9, 17, 4, 20, 40, 743885, tzinfo=datetime.timezone.utc)),
        ),
    ]
