# Generated by Django 4.0.6 on 2022-08-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0004_servidor_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
