# Generated by Django 4.0.6 on 2022-08-21 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidor', '0002_alter_servidor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('contrato', models.TextField(max_length=10)),
                ('numero_de_processo', models.TextField(db_column='numeroDeProcesso', max_length=50)),
                ('objeto', models.TextField(max_length=100)),
                ('empresa', models.TextField(max_length=100)),
                ('data_assinatura', models.DateField()),
                ('data_termino', models.DateField()),
                ('vencimento', models.DateField()),
                ('status', models.TextField()),
                ('observacao', models.TextField()),
                ('id_servidor_gestor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servidor.servidor')),
            ],
        ),
    ]
