# Generated by Django 4.0.6 on 2022-08-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_alter_contrato_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='id_servidor_gestor',
            new_name='servidor_gestor',
        ),
    ]
