# Generated by Django 4.0.6 on 2022-08-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_rename_id_servidor_gestor_contrato_servidor_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
