# Generated by Django 4.0.6 on 2022-08-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0004_alter_contrato_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
