# Generated by Django 4.0.6 on 2022-08-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0005_contrato_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='contato_da_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
