# Generated by Django 4.0.6 on 2022-08-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0007_contrato_email_da_empresa_contrato_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='contrato',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_de_processo',
            field=models.CharField(db_column='numeroDeProcesso', max_length=50),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='objeto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('TRAMITANDO', 'TRAMITANDO'), ('INATIVO', 'INATIVO')], max_length=20),
        ),
    ]
