# Generated by Django 4.0.6 on 2022-08-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0008_alter_contrato_contrato_alter_contrato_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='observacao',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
