# Generated by Django 4.0.6 on 2022-08-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0009_alter_contrato_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
